### ISSUE TITLE
Doesn't work with 0.3.0?

### ISSUE THREAD

**Issue by GregFrench** [ngokevin/aframe-text-component#16]
The text component works perfectly fine with version 0.2.0 but when I switch it to version 0.3.0 it doesn't work.

**Comment by RSpace** [comment]
Works for me in 0.3.0 with the newest dist at https://raw.githubusercontent.com/ngokevin/aframe-text-component/master/dist/aframe-text-component.min.js. Renders a bit differently, though.

**Comment by GregFrench** [comment]
Yep, works for me now. Turns out I just needed to modify the position to get it to work properly. Thanks, Casper!
