### ISSUE TITLE
Letter Spacing & Multiline

### ISSUE THREAD

**Issue by pr1ntr** [ngokevin/aframe-text-component#17]
is general letter spacing possible? Is wrapping the text possible? Not sure, I don't see anything in the docs. Thanks.

**Comment by LukePOWSTER** [comment]
Seconded - currently wracking my brain trying to find a property somewhere for multi-line wrapping...

**Comment by pr1ntr** [comment]
Meanwhile in the future.... "So i just finished this responsive vr layout, but I wish EDGE 2045 would support the latest neural input protocol. Ever since MS and Apple merged they have really been behind the times" 

:P

**Comment by ngokevin** [comment]
https://github.com/bryik/aframe-bmfont-text-component does line wrapping (using a different implementation of text).

Or any of the HTML-to-canvas solutions if you want layout like https://github.com/mayognaise/aframe-html-shader or https://github.com/scenevr/htmltexture-component

For this component, you'd create different text entities per line. You can write helper components or functions to do that for you. This just uses three.js TextGeometry, I don't think there is a letter-spacing option.

Also this repo has moved to https://github.com/ngokevin/kframe
