### ISSUE TITLE
default export or component?

### ISSUE THREAD

**Issue by mattdesl** [ngokevin/aframe-text-component#2]
The readme uses this format:
```js
AFrame = require('aframe-core');
AFrame.registerComponent('text', require('aframe-text-component'));
```

However, the `examples/main` uses this:

```js
require('../index.js').component
```

I am guessing the latter is correct? Is there any reason `module.exports.component` is encouraged over just `module.exports`?

**Comment by ngokevin** [comment]
Thanks for catching that, it should be `.component`.

I like exporting it as `component` rather than default export as it gives more flexibility to export extra stuff like multiple components, utility functions, exporting things to unit test, etc.

**Comment by ngokevin** [comment]
Now does auto-registration.
