### ISSUE TITLE
[Question] Rotating text

### ISSUE THREAD

**Issue by enilsen16** [ngokevin/aframe-text-component#3]
I am trying to rotate some text using `a-animation` around the z-axis centered in the text block. It is rotating around the z-axis but is anchored on the left side of the text block. Is there a way to change the starting point of the rotation?

```
    <a-entity text="text: Hello World!" material="color: #66E1B4" position="-3 1.25 -1">
      <a-animation attribute="rotation" to="0 360 0" dur="10000" fill="forwards" repeat="indefinite"></a-animation>
    </a-entity>
```

**Comment by ngokevin** [comment]
You can apply the animation to a parent entity, something like:

```html
<a-entity>
  <a-entity text="text: Hello World!" position="0 0 20"></a-entity>
  <a-animation attribute="rotation"></a-animation>
```

**Comment by enilsen16** [comment]
Thanks :smile:
