### ISSUE TITLE
How to integrate into Ruby on Rails?

### ISSUE THREAD

**Issue by jamessteininger** [ngokevin/aframe-text-component#4]
How do I install into a Ruby application?

**Comment by ngokevin** [comment]
Not sure this makes sense since A-Frame components are frontend modules. Let me know if you have more clarification.

**Comment by jamessteininger** [comment]
I was being silly, I added the minified js file into the page I'm experimenting with, realized of course I don't need to go through the NPM to install this. In Firefox this script causes a crash though, even if I'm not calling a function to add a text entity-just including the script causes the crash.

**Comment by JonathanGrant** [comment]
Did you eventually figure this out? I'm having problems with this too: http://stackoverflow.com/questions/40643410/im-having-trouble-including-aframe-in-the-asset-pipeline-of-my-rails-applicatio
