### ISSUE TITLE
Integrate with main aframe.js

### ISSUE THREAD

**Issue by unexpector** [ngokevin/aframe-text-component#6]
I am having issues getting this to work with aframe.js
Currently it only works with aframe-core

Is there a way to get this working with  https://github.com/aframevr/aframe ?

**Comment by ngokevin** [comment]
Hm, this should work with `aframe`. What's happening?

But I will work on getting this into `aframe` repo later.

**Comment by chchrist** [comment]
Hello with latest aframe.js I get
```
Uncaught TypeError: this.el.getOrCreateObject3D is not a function
module.exports.component.update @ aframe-text-component.js:99
module.exports.Component @ aframe.js:59248
NewComponent @ aframe.js:59404
proto.initComponent.value @ aframe.js:57738
proto.updateComponent.value @ aframe.js:57819
updateComponent @ aframe.js:57779
proto.updateComponents.value @ aframe.js:57776
proto.load.value @ aframe.js:57679
proto.attachedCallback.value @ aframe.js:57569
wrapperMethod @ aframe.js:58368
```

**Comment by ngokevin** [comment]
You can use latest latest A-Frame https://github.com/aframevr/aframe/tree/dev/dist

Or check out older version https://github.com/ngokevin/aframe-text-component/tree/903f2285c5e3a8fdc5d14e631532670ef0a9a293
