### ISSUE TITLE
New line

### ISSUE THREAD

**Issue by joelnz** [ngokevin/aframe-text-component#7]
Hi
Is there a way to do a line break without having to create a new entity. 

something
like
this

Love the component!

**Comment by msimpson** [comment]
@joelnz 
This component utilizes the underlying THREE.TextGeometry class which only supports a single line at the moment.

**Comment by ngokevin** [comment]
Try using the layout component https://github.com/ngokevin/aframe-layout-component

Or a better text component https://github.com/bryik/aframe-bmfont-text-component
