### ISSUE TITLE
Non-ascii support?

### ISSUE THREAD

**Issue by rafaeleyng** [ngokevin/aframe-text-component#9]
Hello there. Awesome job!

I'm using the text component in a project and I would like to use non-ascii characters, such as **ó**, **ã**, **º**. When using some of those characters, they appear as **?**.

Is this currently possible? How would I do it? If not, do you have plans for this?

**Comment by rafaeleyng** [comment]
Hm, I've tried a couple of things in the fonts demo and this seems to be font-related:

![image](https://cloud.githubusercontent.com/assets/4842605/16717279/54cf8a8e-46e9-11e6-940d-4d069cca6132.png)

I will try to use a different font then. Just leaving the issue open to check if there's more to this matter.

**Comment by ngokevin** [comment]
Probably the font, but also try https://github.com/bryik/aframe-bmfont-text-component
